name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    
    env:
      Solution_Name: FlickerImageSearch.sln
      #Test_Project_Path: your-test-project-path
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.6

    - name: Restore Nuget packages
      run: nuget restore $env:Solution_Name

    - name: Build the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
